# Generated by Django 6.0.2 on 2026-02-05 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('participants', models.CharField(blank=True, max_length=500, null=True)),
                ('reminder', models.PositiveIntegerField(default=15, help_text='Reminder minutes before')),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('meeting', 'Meeting'), ('appointment', 'Appointment'), ('other', 'Other')], default='work', max_length=32)),
                ('caldav_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('caldav_href', models.CharField(blank=True, max_length=512, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
