"""
Django settings for autoplanner project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv()

# Allow OAuth over HTTP in development (required for localhost testing)
# PRODUCTION: This MUST be false to use HTTPS only
if os.getenv('ENVIRONMENT') == 'development' and os.getenv('OAUTHLIB_INSECURE_TRANSPORT', '').lower() == 'true':
    os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY and os.getenv('ENVIRONMENT') != 'development':
    raise ValueError("DJANGO_SECRET_KEY environment variable is not set!")
if not SECRET_KEY:
    SECRET_KEY = 'dev-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Cloud Run specific settings
if os.getenv('ENVIRONMENT') == 'production':
    DEBUG = False
    # Get allowed hosts from env var, fallback to allowing all *.run.app domains for Cloud Run
    allowed_hosts = os.getenv('DJANGO_ALLOWED_HOSTS', '').strip()
    if allowed_hosts:
        ALLOWED_HOSTS = [h.strip() for h in allowed_hosts.split(',') if h.strip()]
    else:
        # Allow all Cloud Run domains
        ALLOWED_HOSTS = ['*']
    # Cloud Run uses Google Frontend Load Balancer which handles SSL/TLS
    # The request arrives to the Django app already as HTTPS, but Django sees it as HTTP
    # We need to trust the X-Forwarded-Proto header from the Load Balancer
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # Disable SSL redirect as load balancer handles it
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
    'events',
    'google_sync',
    'ai',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'autoplanner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'autoplanner.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv('ENVIRONMENT') == 'production':
    # Use Cloud SQL in production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'autoplanner'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': f'/cloudsql/{os.getenv("CLOUD_SQL_CONNECTION_NAME")}',
            'PORT': '5432',
        }
    }
else:
    # Use SQLite in development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

# Default to LA time unless explicitly overridden
TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'America/Los_Angeles')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Cloud Storage for static files in production
if os.getenv('ENVIRONMENT') == 'production':
    try:
        from storages.backends.gcloud import GoogleCloudStorage
        DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
        GS_BUCKET_NAME = os.getenv('GCS_BUCKET_NAME', 'autoplanner-static')
        GS_PROJECT_ID = os.getenv('GCP_PROJECT_ID', '')
        STATIC_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/static/'
    except ImportError:
        # Fall back to local static files if google-cloud-storage is not installed
        pass

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Google Generative AI
GOOGLE_GENERATIVE_AI_KEY = os.getenv('GOOGLE_GENERATIVE_AI_KEY', '')
GOOGLE_GENERATIVE_AI_MODEL = os.getenv('GOOGLE_GENERATIVE_AI_MODEL', 'gemini-2.5-flash')

# Radicale (CalDAV) settings
RADICALE_BASE_URL = os.getenv('RADICALE_BASE_URL', 'https://localhost:5232')
RADICALE_VERIFY_SSL = os.getenv('RADICALE_VERIFY_SSL', 'false').lower() == 'true'
RADICALE_DEFAULT_CALENDAR = os.getenv('RADICALE_DEFAULT_CALENDAR', 'calendar')
RADICALE_HTPASSWD_PATH = os.getenv(
    'RADICALE_HTPASSWD_PATH',
    str(Path.home() / 'magic-calendar' / 'radicale_config' / 'users'),
)
RADICALE_HTPASSWD_ENCRYPTION = os.getenv('RADICALE_HTPASSWD_ENCRYPTION', 'plain')
RADICALE_CONFIG_PATH = os.getenv(
    'RADICALE_CONFIG_PATH',
    str(Path.home() / 'magic-calendar' / 'radicale_config' / 'config'),
)

# Google OAuth (Calendar)
GOOGLE_OAUTH_CLIENT_JSON_PATH = os.getenv(
    'GOOGLE_OAUTH_CLIENT_JSON_PATH',
    str(BASE_DIR / 'webclient.json'),
)
GOOGLE_OAUTH_REDIRECT_URI = os.getenv(
    'GOOGLE_OAUTH_REDIRECT_URI',
    'http://localhost:8000/oauth/google/callback',
)
GOOGLE_OAUTH_SCOPES = os.getenv(
    'GOOGLE_OAUTH_SCOPES',
    'https://www.googleapis.com/auth/calendar.events',
)

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'json': {
            'format': '{{"time": "{asctime}", "level": "{levelname}", "message": "{message}", "module": "{module}"}}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json' if os.getenv('ENVIRONMENT') == 'production' else 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('LOG_LEVEL', 'INFO'),
    },
}
