"""
Django settings for autoplanner project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv()

# Allow OAuth over HTTP in development (required for localhost testing)
if os.getenv('OAUTHLIB_INSECURE_TRANSPORT', '').lower() == 'true':
    import os
    os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
    'events',
    'caldav_sync',
    'google_sync',
    'ai',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'autoplanner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'autoplanner.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

# Default to LA time unless explicitly overridden
TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'America/Los_Angeles')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [BASE_DIR / 'static']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Google Generative AI
GOOGLE_GENERATIVE_AI_KEY = os.getenv('GOOGLE_GENERATIVE_AI_KEY', '')
GOOGLE_GENERATIVE_AI_MODEL = os.getenv('GOOGLE_GENERATIVE_AI_MODEL', 'gemini-2.0-flash')

# Radicale (CalDAV) settings
RADICALE_BASE_URL = os.getenv('RADICALE_BASE_URL', 'https://localhost:5232')
RADICALE_VERIFY_SSL = os.getenv('RADICALE_VERIFY_SSL', 'false').lower() == 'true'
RADICALE_DEFAULT_CALENDAR = os.getenv('RADICALE_DEFAULT_CALENDAR', 'calendar')
RADICALE_HTPASSWD_PATH = os.getenv(
    'RADICALE_HTPASSWD_PATH',
    str(Path.home() / 'magic-calendar' / 'radicale_config' / 'users'),
)
RADICALE_HTPASSWD_ENCRYPTION = os.getenv('RADICALE_HTPASSWD_ENCRYPTION', 'plain')
RADICALE_CONFIG_PATH = os.getenv(
    'RADICALE_CONFIG_PATH',
    str(Path.home() / 'magic-calendar' / 'radicale_config' / 'config'),
)

# Google OAuth (Calendar)
GOOGLE_OAUTH_CLIENT_JSON_PATH = os.getenv(
    'GOOGLE_OAUTH_CLIENT_JSON_PATH',
    str(BASE_DIR / 'webclient.json'),
)
GOOGLE_OAUTH_REDIRECT_URI = os.getenv(
    'GOOGLE_OAUTH_REDIRECT_URI',
    'http://localhost:8000/oauth/google/callback',
)
GOOGLE_OAUTH_SCOPES = os.getenv(
    'GOOGLE_OAUTH_SCOPES',
    'https://www.googleapis.com/auth/calendar.events',
)
